default_ambiguity_set: base_test_case

ambiguity_sets:
  base_test_case:
    description: Regime ambiguity set for base PoA analysis.

    demand:
      mu:
        min: 0.75
        max: 1.25
      sigma:
        min: 0.001
        max: 0.025
      rho_fixed: 0.75

    wind:
      mu:
        min: 0.25
        max: 0.75
      sigma:
        min: 0.001
        max: 0.025
      rho_fixed: 0.75
      tau_fixed: 14

    kappa: 0.3
