"""Verification script for DROWassersteinSupportSet.

Three checks, run on two scenario sources:
  - EXISTING: the scenarios already generated by the DRO pipeline
    (constrained to the old DROPoASupportSet).  These should always pass
    the new AR(1)-only tube because the new kappa is larger than the old one.
  - FRESH: N_DRAWS unconstrained draws from the regime distribution.
    Use these to pick the smallest kappa that gives 0% rejection on raw draws.

Check 1 — Whitened-innovation histogram
  xi_0 = D[0] - D_ref*mu_D*shape[0]
  xi_t = D[t] - rho_D*D[t-1] - D_ref*mu_D*(shape[t] - rho_D*shape[t-1])  for t >= 1
  Expected: N(0, (D_ref*sigma_D)^2).  Same formula for wind, with P_W_max*sigma_W.

Check 2 — Rejection-rate sweep
  Fraction of trajectories where any time step violates the AR(1) tube,
  scanned over a grid of coverage values.  Chosen coverage should give 0%.

Check 3 — Sawtooth adversarial test
  An alternating max/min path has innovations ~ rho * physical_range >> tube width.
  The tube should always reject it; if not, coherence must move to the transport cost.

Usage:
    .venv/Scripts/python.exe driver/verify_dro_support.py
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path
from typing import Any

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import norm as _norm

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.scenarios.scenario_generator import ScenarioManager
from models.DRO_PoA.dro_poa_model.support_set import _ar1_kappa


# ---------------------------------------------------------------------------
# Configuration — edit here
# ---------------------------------------------------------------------------
CASE = "base_test_case"
REGIME_CONFIG = Path("config/regime_definitions.yaml")
REGIME_SET = "PoA_analysis"
REGIME_NAME = "normal"
HORIZON = 8
N_DRAWS = 2000          # fresh draws for statistical checks
VERIFY_SEED = 77777     # separate from training/DRO seeds
CHOSEN_COVERAGE = 0.99  # coverage intended for DROWassersteinSupportSet
OUTPUT_DIR = Path("results/verify_dro_support")
COVERAGE_GRID = [0.90, 0.95, 0.99, 0.999, 0.9999]
# Path to the scenarios already generated by the DRO pipeline.
# Set to None to skip the existing-scenarios check.
EXISTING_SCENARIOS_CSV = Path("results/full_pipeline_DRO/dro_scenarios/scenarios.csv")
# ---------------------------------------------------------------------------


def _parse_profile(v: Any) -> list[float]:
    if isinstance(v, (list, np.ndarray)):
        return [float(x) for x in v]
    return [float(x) for x in ast.literal_eval(str(v))]


def _build_wind_profiles(
    df: pd.DataFrame,
    manager: ScenarioManager,
    N: int,
    T: int,
) -> dict[str, tuple[np.ndarray, float]]:
    """Return {gen_name: (profiles (N,T) in MW, P_W_max)} for all wind generators.

    The {block_name}_profile column stores wind_factor * block_pmax / phys_pmax
    (a dimensionless fraction of physical pmax per block).  To recover P[t] in MW
    for the whole physical generator, multiply each block's stored value by phys_pmax
    and sum — which equals wind_factor * sum(block_pmax) = wind_factor * phys_pmax.
    """
    result: dict[str, tuple[np.ndarray, float]] = {}
    for g in manager.physical_generators:
        if not bool(g["is_wind"]):
            continue
        name = g["physical_name"]
        P_W_max = float(g["pmax"])
        blocks = [b for b in manager.blocks if b["physical_name"] == name and bool(b["is_wind"])]
        profiles = np.zeros((N, T), dtype=float)
        for b in blocks:
            col = f"{b['block_name']}_profile"
            if col not in df.columns:
                continue
            # The scenario generator stores {block_name}_profile[t] = wind_factor[t] * block_pmax,
            # which is already in MW.  Summing over all blocks of the same physical generator
            # gives wind_factor[t] * sum(block_pmax) = wind_factor[t] * phys_pmax = P[t] in MW.
            # No additional scaling is needed.
            profiles += np.array(
                [_parse_profile(df.at[s, col]) for s in range(N)],
                dtype=float,
            )
        result[name] = (profiles, P_W_max)
    return result


# ---------------------------------------------------------------------------
# Innovation computation
# ---------------------------------------------------------------------------

def _demand_innovations(
    demand_profiles: np.ndarray,  # (N, T) in MW
    demand_shape: np.ndarray,
    mu_D: float,
    rho_D: float,
    D_ref: float,
) -> np.ndarray:
    """Whitened demand innovations (N, T).  Expected ~ N(0, (D_ref*sigma_D)^2)."""
    N, T = demand_profiles.shape
    xi = np.zeros((N, T), dtype=float)
    xi[:, 0] = demand_profiles[:, 0] - D_ref * mu_D * demand_shape[0]
    if T > 1:
        ref = D_ref * mu_D * (demand_shape[1:] - rho_D * demand_shape[:-1])
        xi[:, 1:] = demand_profiles[:, 1:] - rho_D * demand_profiles[:, :-1] - ref
    return xi


def _wind_innovations(
    wind_profiles: np.ndarray,  # (N, T) in MW
    wind_shape: np.ndarray,
    mu_W: float,
    rho_W: float,
    P_W_max: float,
) -> np.ndarray:
    """Whitened wind innovations (N, T).  Expected ~ N(0, (P_W_max*sigma_W)^2)
    for unclipped draws; the [0, P_W_max] clip truncates the tails slightly."""
    N, T = wind_profiles.shape
    xi = np.zeros((N, T), dtype=float)
    xi[:, 0] = wind_profiles[:, 0] - P_W_max * mu_W * wind_shape[0]
    if T > 1:
        ref = P_W_max * mu_W * (wind_shape[1:] - rho_W * wind_shape[:-1])
        xi[:, 1:] = wind_profiles[:, 1:] - rho_W * wind_profiles[:, :-1] - ref
    return xi


def _rejection_rate(innovations: np.ndarray, sigma: float, kappa: float) -> float:
    """Fraction of trajectories where any step violates the kappa*sigma tube."""
    return float(np.mean(np.any(np.abs(innovations) > kappa * sigma, axis=1)))


# ---------------------------------------------------------------------------
# Check 1 — histogram
# ---------------------------------------------------------------------------

def check_innovations(
    innovations: np.ndarray,
    sigma_innov: float,
    label: str,
    output_dir: Path,
) -> None:
    xi = innovations.flatten()
    mean = float(np.mean(xi))
    std = float(np.std(xi))
    skew = float(np.mean(((xi - mean) / std) ** 3)) if std > 0 else float("nan")

    print(f"\n  {label}:")
    print(f"    n            = {len(xi)}")
    print(f"    mean         = {mean:.4g}  (expected 0)")
    print(f"    std          = {std:.4g}  (expected {sigma_innov:.4g})")
    print(f"    std/expected = {std / sigma_innov:.4f}  (should be ~1.0)")
    print(f"    skewness     = {skew:.4f}  (expected ~0; clipping shifts wind)")

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    bins = min(80, max(30, len(xi) // 40))
    ax.hist(xi, bins=bins, density=True, alpha=0.6, label="draws")
    x_grid = np.linspace(xi.min(), xi.max(), 400)
    ax.plot(x_grid, _norm.pdf(x_grid, 0.0, sigma_innov), "r-", lw=2,
            label=f"N(0, {sigma_innov:.3g}²)")
    ax.set_xlabel("Whitened innovation xi")
    ax.set_ylabel("Density")
    ax.set_title(label)
    ax.legend()
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    path = output_dir / f"innovations_{label.lower().replace(' ', '_').replace('/', '_')}.png"
    fig.savefig(path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"    Saved: {path}")


# ---------------------------------------------------------------------------
# Check 2 — rejection rate sweep
# ---------------------------------------------------------------------------

def check_rejection_rates(
    demand_xi: np.ndarray,
    wind_xi_by_gen: dict[str, np.ndarray],
    sigma_D: float,
    sigma_W_by_gen: dict[str, float],
    T: int,
    chosen_coverage: float,
) -> None:
    print("\n  Rejection rate vs. coverage (any step violating tube, any generator):")
    print(f"  {'Coverage':>10}  {'kappa':>8}  {'Demand%':>10}  {'Wind% max':>12}")
    print("  " + "-" * 46)
    for cov in COVERAGE_GRID:
        kappa = _ar1_kappa(T, cov)
        d = _rejection_rate(demand_xi, sigma_D, kappa) * 100
        w = max((_rejection_rate(xi, sigma_W_by_gen[g], kappa) * 100
                 for g, xi in wind_xi_by_gen.items()), default=float("nan"))
        mark = " <-- chosen" if abs(cov - chosen_coverage) < 1e-9 else ""
        print(f"  {cov:>10.4f}  {kappa:>8.4f}  {d:>9.2f}%  {w:>11.2f}%{mark}")


# ---------------------------------------------------------------------------
# Check 3 — sawtooth
# ---------------------------------------------------------------------------

def check_sawtooth(
    demand_shape: np.ndarray,
    wind_shape: np.ndarray,
    D_ref: float,
    mu_D: float,
    sigma_D: float,
    rho_D: float,
    P_W_max: float,
    mu_W: float,
    sigma_W: float,
    rho_W: float,
    total_capacity: float,
    T: int,
    chosen_coverage: float,
) -> None:
    kappa = _ar1_kappa(T, chosen_coverage)
    thr_D = kappa * D_ref * sigma_D
    thr_W = kappa * P_W_max * sigma_W

    D_saw = np.where(np.arange(T) % 2 == 0, total_capacity, 0.0)
    xi_D = _demand_innovations(D_saw[np.newaxis, :], demand_shape, mu_D, rho_D, D_ref)[0]
    d_viol = bool(np.any(np.abs(xi_D) > thr_D))

    W_saw = np.where(np.arange(T) % 2 == 0, P_W_max, 0.0)
    xi_W = _wind_innovations(W_saw[np.newaxis, :], wind_shape, mu_W, rho_W, P_W_max)[0]
    w_viol = bool(np.any(np.abs(xi_W) > thr_W))

    print(f"\n  Sawtooth adversarial test (coverage={chosen_coverage}, kappa={kappa:.4f}):")
    print(f"    Demand: max|xi|={np.max(np.abs(xi_D)):.4g}  threshold={thr_D:.4g}  "
          f"REJECTED={d_viol}")
    print(f"    Wind:   max|xi|={np.max(np.abs(xi_W)):.4g}  threshold={thr_W:.4g}  "
          f"REJECTED={w_viol}")
    if not d_viol or not w_viol:
        print("  WARNING: sawtooth NOT fully rejected. Physical range too narrow relative "
              "to the tube — coherence should move into the transport cost.")
    else:
        print("  OK: sawtooth correctly rejected by the AR(1) tube.")


# ---------------------------------------------------------------------------
# Single-source runner
# ---------------------------------------------------------------------------

def _run_all_checks(
    df: pd.DataFrame,
    manager: ScenarioManager,
    source_label: str,
    output_dir: Path,
) -> None:
    N = len(df)
    T = HORIZON
    mu_D = float(df.at[0, "mu_D"])
    sigma_D = float(df.at[0, "sigma_D"])
    rho_D = float(df.at[0, "rho_D"])
    mu_W = float(df.at[0, "mu_W"])
    sigma_W = float(df.at[0, "sigma_W"])
    rho_W = float(df.at[0, "rho_W"])
    peak_W = float(df.at[0, "peak_W"])
    D_ref = float(manager.base_case["demand"])

    demand_shape = ScenarioManager._build_demand_shape(T)
    wind_shape = ScenarioManager._build_wind_shape(T, peak_W)

    demand_profiles = np.array([_parse_profile(df.at[s, "demand_profile"]) for s in range(N)])
    wind_gen_data = _build_wind_profiles(df, manager, N, T)
    total_capacity = sum(float(g["pmax"]) for g in manager.physical_generators)

    sigma_D_innov = D_ref * sigma_D
    demand_xi = _demand_innovations(demand_profiles, demand_shape, mu_D, rho_D, D_ref)

    wind_xi_by_gen: dict[str, np.ndarray] = {}
    sigma_W_by_gen: dict[str, float] = {}
    for name, (wp, P_W_max) in wind_gen_data.items():
        wind_xi_by_gen[name] = _wind_innovations(wp, wind_shape, mu_W, rho_W, P_W_max)
        sigma_W_by_gen[name] = P_W_max * sigma_W

    kappa_chosen = _ar1_kappa(T, CHOSEN_COVERAGE)

    print(f"\n{'=' * 60}")
    print(f"Source: {source_label}  (N={N}, regime='{REGIME_NAME}', T={T})")
    print(f"Regime: mu_D={mu_D}, sigma_D={sigma_D}, rho_D={rho_D}")
    print(f"        mu_W={mu_W}, sigma_W={sigma_W}, rho_W={rho_W}")
    print(f"{'=' * 60}")

    print("\n--- Check 1: Whitened innovations ---")
    check_innovations(demand_xi, sigma_D_innov, f"Demand [{source_label}]", output_dir)
    for name, xi_w in wind_xi_by_gen.items():
        check_innovations(xi_w, sigma_W_by_gen[name],
                          f"Wind {name} [{source_label}]", output_dir)

    print("\n--- Check 2: Rejection rate sweep ---")
    check_rejection_rates(demand_xi, wind_xi_by_gen, sigma_D_innov,
                          sigma_W_by_gen, T, CHOSEN_COVERAGE)

    print("\n--- Check 3: Sawtooth adversarial test ---")
    first_wind = next(iter(wind_gen_data.values()), None)
    P_W_max_saw = first_wind[1] if first_wind else 0.0
    check_sawtooth(
        demand_shape=demand_shape, wind_shape=wind_shape,
        D_ref=D_ref, mu_D=mu_D, sigma_D=sigma_D, rho_D=rho_D,
        P_W_max=P_W_max_saw, mu_W=mu_W, sigma_W=sigma_W, rho_W=rho_W,
        total_capacity=total_capacity, T=T, chosen_coverage=CHOSEN_COVERAGE,
    )

    d_rej = _rejection_rate(demand_xi, sigma_D_innov, kappa_chosen) * 100
    w_rej = max((_rejection_rate(xi, sigma_W_by_gen[g], kappa_chosen) * 100
                 for g, xi in wind_xi_by_gen.items()), default=float("nan"))
    print(f"\n--- Summary [{source_label}] ---")
    print(f"  coverage={CHOSEN_COVERAGE}  kappa={kappa_chosen:.4f}")
    print(f"  Demand rejection: {d_rej:.2f}%  (target 0%)")
    print(f"  Wind rejection (max across generators): {w_rej:.2f}%  (target 0%)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    manager = ScenarioManager(CASE)
    manager.base_case["time_steps"] = HORIZON

    # ---- Existing DRO scenarios ----
    if EXISTING_SCENARIOS_CSV is not None and EXISTING_SCENARIOS_CSV.exists():
        print(f"\nLoading existing DRO scenarios from {EXISTING_SCENARIOS_CSV}")
        existing_df = pd.read_csv(EXISTING_SCENARIOS_CSV)
        if "regime" in existing_df.columns:
            existing_df = existing_df[existing_df["regime"] == REGIME_NAME].reset_index(drop=True)
        if len(existing_df) == 0:
            print(f"  No rows for regime '{REGIME_NAME}' — skipping existing-scenario check.")
        else:
            _run_all_checks(existing_df, manager, "existing DRO scenarios", OUTPUT_DIR)
    else:
        if EXISTING_SCENARIOS_CSV is not None:
            print(f"\nExisting-scenarios CSV not found: {EXISTING_SCENARIOS_CSV}")
        print("Skipping existing-scenario check.")

    # ---- Fresh draws ----
    print(f"\nGenerating {N_DRAWS} fresh draws (seed={VERIFY_SEED}) ...")
    raw = manager.create_scenario_set_from_regimes(
        regime_config_path=str(REGIME_CONFIG),
        regime_set=REGIME_SET,
        seed=VERIFY_SEED,
    )
    fresh_df = raw["scenarios_df"]
    if "regime" in fresh_df.columns:
        fresh_df = fresh_df[fresh_df["regime"] == REGIME_NAME].reset_index(drop=True)
    if len(fresh_df) == 0:
        print(f"No scenarios generated for regime '{REGIME_NAME}'. "
              f"Available: {raw['scenarios_df']['regime'].unique().tolist()}")
        return
    fresh_df = fresh_df.iloc[:N_DRAWS].reset_index(drop=True)
    _run_all_checks(fresh_df, manager, "fresh draws (unconstrained)", OUTPUT_DIR)


if __name__ == "__main__":
    main()
