"""Verification script for DROWassersteinSupportSet.

Four check families, run on two scenario sources:
  - EXISTING: scenarios from the DRO pipeline (constrained to old DROPoASupportSet).
  - FRESH: N_DRAWS unconstrained draws from the regime distribution.

Check 1 — Whitened-innovation histograms + stationary level-deviation histograms.
Check 2 — Rejection-rate sweeps: AR(1) innovations, level band (demand + wind),
           fleet aggregate band.
Check 3 — Sawtooth adversarial test (innovation tube rejects fast oscillations).
Check 4 — Innovation-stack and fleet-stack corner tests: trajectories that stay
           inside the AR(1) tube but accumulate level drift — the new bands must
           reject them.

Usage:
    .venv/Scripts/python.exe driver_tmp/verify_dro_support.py
"""
from __future__ import annotations

import ast
import json
import sys
import tempfile
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import yaml
from scipy.stats import norm as _norm

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.scenarios.scenario_generator import ScenarioManager
from models.DRO_PoA.dro_poa_model.support_set import _ar1_kappa


# ---------------------------------------------------------------------------
# Configuration — edit here
# ---------------------------------------------------------------------------
CASE = "base_test_case"
REGIME_CONFIG = Path("config/regime_definitions.yaml")
REGIME_SET = "PoA_analysis"
REGIME_NAME = "normal"
HORIZON = 8
N_DRAWS = 2000
VERIFY_SEED = 77777
CHOSEN_COVERAGE = 0.99        # AR(1) innovation tube coverage
CHOSEN_LEVEL_COVERAGE = 0.9999  # stationary level band (matches LEVEL_JOINT_COVERAGE)
CHOSEN_FLEET_COVERAGE = 0.999   # fleet aggregate band (matches FLEET_JOINT_COVERAGE)
OUTPUT_DIR = Path("results/verify_dro_support")
COVERAGE_GRID = [0.90, 0.95, 0.99, 0.999, 0.9999]
RUN_SUPPORT_COVERAGE_CALIBRATION = True
CALIBRATION_N_DRAWS = N_DRAWS
CALIBRATION_SEED = VERIFY_SEED
SUPPORT_CALIBRATION_REPORT_PATH = OUTPUT_DIR / "support_coverage_calibration.json"
# Path to scenarios already generated by the DRO pipeline.  Set to None to skip.
EXISTING_SCENARIOS_CSV = Path("results/full_pipeline_DRO/dro_scenarios/scenarios.csv")
# ---------------------------------------------------------------------------


def _parse_profile(v: Any) -> list[float]:
    if isinstance(v, (list, np.ndarray)):
        return [float(x) for x in v]
    return [float(x) for x in ast.literal_eval(str(v))]


def _build_wind_profiles(
    df: pd.DataFrame,
    manager: ScenarioManager,
    N: int,
    T: int,
) -> dict[str, tuple[np.ndarray, float]]:
    """Return {gen_name: (profiles (N,T) in MW, P_W_max)} for all wind generators."""
    result: dict[str, tuple[np.ndarray, float]] = {}
    for g in manager.physical_generators:
        if not bool(g["is_wind"]):
            continue
        name = g["physical_name"]
        P_W_max = float(g["pmax"])
        blocks = [b for b in manager.blocks if b["physical_name"] == name and bool(b["is_wind"])]
        profiles = np.zeros((N, T), dtype=float)
        for b in blocks:
            col = f"{b['block_name']}_profile"
            if col not in df.columns:
                continue
            profiles += np.array(
                [_parse_profile(df.at[s, col]) for s in range(N)],
                dtype=float,
            )
        result[name] = (profiles, P_W_max)
    return result


# ---------------------------------------------------------------------------
# Innovation / level deviation computation
# ---------------------------------------------------------------------------


def _demand_innovations(
    demand_profiles: np.ndarray,
    demand_shape: np.ndarray,
    mu_D: float,
    rho_D: float,
    D_ref: float,
) -> np.ndarray:
    """Whitened demand innovations (N, T).  Expected ~ N(0, (D_ref*sigma_D)^2)."""
    N, T = demand_profiles.shape
    xi = np.zeros((N, T), dtype=float)
    xi[:, 0] = demand_profiles[:, 0] - D_ref * mu_D * demand_shape[0]
    if T > 1:
        ref = D_ref * mu_D * (demand_shape[1:] - rho_D * demand_shape[:-1])
        xi[:, 1:] = demand_profiles[:, 1:] - rho_D * demand_profiles[:, :-1] - ref
    return xi


def _wind_innovations(
    wind_profiles: np.ndarray,
    wind_shape: np.ndarray,
    mu_W: float,
    rho_W: float,
    P_W_max: float,
) -> np.ndarray:
    """Whitened wind innovations (N, T).  Expected ~ N(0, (P_W_max*sigma_W)^2)."""
    N, T = wind_profiles.shape
    xi = np.zeros((N, T), dtype=float)
    xi[:, 0] = wind_profiles[:, 0] - P_W_max * mu_W * wind_shape[0]
    if T > 1:
        ref = P_W_max * mu_W * (wind_shape[1:] - rho_W * wind_shape[:-1])
        xi[:, 1:] = wind_profiles[:, 1:] - rho_W * wind_profiles[:, :-1] - ref
    return xi


def _demand_level_dev(
    demand_profiles: np.ndarray,
    demand_shape: np.ndarray,
    mu_D: float,
    D_ref: float,
) -> np.ndarray:
    """Level deviation from stationary reference (N, T).  Expected std = D_ref*sigma_bar_D."""
    ref = D_ref * mu_D * demand_shape[np.newaxis, :]
    return demand_profiles - ref


def _wind_level_dev(
    wind_profiles: np.ndarray,
    wind_shape: np.ndarray,
    mu_W: float,
    cap: float,
) -> np.ndarray:
    """Wind level deviation from stationary reference (N, T).  Expected std = cap*sigma_bar_W."""
    ref = cap * mu_W * wind_shape[np.newaxis, :]
    return wind_profiles - ref


def _rejection_rate(deviations: np.ndarray, sigma: float, kappa: float) -> float:
    """Fraction of trajectories where any time step violates the kappa*sigma tube."""
    return float(np.mean(np.any(np.abs(deviations) > kappa * sigma, axis=1)))


# ---------------------------------------------------------------------------
# Check 1 — histogram
# ---------------------------------------------------------------------------


def check_innovations(
    innovations: np.ndarray,
    sigma_innov: float,
    label: str,
    output_dir: Path,
) -> None:
    xi = innovations.flatten()
    mean = float(np.mean(xi))
    std = float(np.std(xi))
    skew = float(np.mean(((xi - mean) / std) ** 3)) if std > 0 else float("nan")

    print(f"\n  {label}:")
    print(f"    n            = {len(xi)}")
    print(f"    mean         = {mean:.4g}  (expected 0)")
    print(f"    std          = {std:.4g}  (expected {sigma_innov:.4g})")
    print(f"    std/expected = {std / sigma_innov:.4f}  (should be ~1.0)")
    print(f"    skewness     = {skew:.4f}  (expected ~0; clipping shifts wind)")

    fig, ax = plt.subplots(figsize=(7.5, 4.5))
    bins = min(80, max(30, len(xi) // 40))
    ax.hist(xi, bins=bins, density=True, alpha=0.6, label="draws")
    x_grid = np.linspace(xi.min(), xi.max(), 400)
    ax.plot(x_grid, _norm.pdf(x_grid, 0.0, sigma_innov), "r-", lw=2,
            label=f"N(0, {sigma_innov:.3g}²)")
    ax.set_xlabel("Whitened innovation / level deviation")
    ax.set_ylabel("Density")
    ax.set_title(label)
    ax.legend()
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    slug = label.lower().replace(" ", "_").replace("/", "_").replace("[", "").replace("]", "")
    path = output_dir / f"innovations_{slug}.png"
    fig.savefig(path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"    Saved: {path}")


# ---------------------------------------------------------------------------
# Check 2 — rejection rate sweeps
# ---------------------------------------------------------------------------


def check_rejection_rates(
    demand_xi: np.ndarray,
    wind_xi_by_gen: dict[str, np.ndarray],
    sigma_D: float,
    sigma_W_by_gen: dict[str, float],
    T: int,
    chosen_coverage: float,
) -> None:
    print("\n  AR(1) innovation rejection rate vs. coverage:")
    print(f"  {'Coverage':>10}  {'kappa':>8}  {'Demand%':>10}  {'Wind% max':>12}")
    print("  " + "-" * 46)
    for cov in COVERAGE_GRID:
        kappa = _ar1_kappa(T, cov)
        d = _rejection_rate(demand_xi, sigma_D, kappa) * 100
        w = max(
            (_rejection_rate(xi, sigma_W_by_gen[g], kappa) * 100 for g, xi in wind_xi_by_gen.items()),
            default=float("nan"),
        )
        mark = " <-- chosen" if abs(cov - chosen_coverage) < 1e-9 else ""
        print(f"  {cov:>10.4f}  {kappa:>8.4f}  {d:>9.2f}%  {w:>11.2f}%{mark}")


def check_level_rejection_rates(
    demand_level_dev: np.ndarray,
    wind_level_devs_by_gen: dict[str, np.ndarray],
    sigma_bar_D: float,
    sigma_bar_W_by_gen: dict[str, float],
    T: int,
    chosen_level_coverage: float,
) -> None:
    print("\n  Stationary level band rejection rate vs. coverage:")
    print(f"  {'Coverage':>10}  {'kappa':>8}  {'Demand%':>10}  {'Wind% max':>12}")
    print("  " + "-" * 46)
    for cov in COVERAGE_GRID:
        kappa = _ar1_kappa(T, cov)
        d = _rejection_rate(demand_level_dev, sigma_bar_D, kappa) * 100
        w = max(
            (_rejection_rate(dev, sigma_bar_W_by_gen[g], kappa) * 100
             for g, dev in wind_level_devs_by_gen.items()),
            default=float("nan"),
        )
        mark = " <-- chosen" if abs(cov - chosen_level_coverage) < 1e-9 else ""
        print(f"  {cov:>10.4f}  {kappa:>8.4f}  {d:>9.2f}%  {w:>11.2f}%{mark}")


def check_fleet_stats(
    fleet_dev: np.ndarray,
    cap_rms_sigma_bar_W: float,
    sum_caps_sigma_bar_W: float,
) -> None:
    """Report fleet empirical std vs. independence-based and per-gen-sum scalings."""
    std_emp = float(np.std(fleet_dev.flatten()))
    ratio_rms = std_emp / cap_rms_sigma_bar_W if cap_rms_sigma_bar_W > 0 else float("nan")
    ratio_sum = std_emp / sum_caps_sigma_bar_W if sum_caps_sigma_bar_W > 0 else float("nan")
    print(f"\n  Fleet level deviation std:")
    print(f"    empirical std          = {std_emp:.4g}")
    print(f"    cap_rms * sigma_bar_W  = {cap_rms_sigma_bar_W:.4g}  (correct, independence-based)")
    print(f"    sum_caps * sigma_bar_W = {sum_caps_sigma_bar_W:.4g}  (loose, per-gen-sum scaling)")
    print(f"    emp / cap_rms          = {ratio_rms:.4f}  (should be ~1.0)")
    print(f"    emp / sum_caps         = {ratio_sum:.4f}  (sqrt(N) gap visible for N > 1)")


def check_fleet_rejection_rates(
    fleet_dev: np.ndarray,
    cap_rms_sigma_bar_W: float,
    T: int,
    chosen_fleet_coverage: float,
) -> None:
    print("\n  Fleet aggregate band rejection rate vs. coverage:")
    print(f"  {'Coverage':>10}  {'kappa':>8}  {'Fleet%':>10}")
    print("  " + "-" * 34)
    for cov in COVERAGE_GRID:
        kappa = _ar1_kappa(T, cov)
        f = _rejection_rate(fleet_dev, cap_rms_sigma_bar_W, kappa) * 100
        mark = " <-- chosen" if abs(cov - chosen_fleet_coverage) < 1e-9 else ""
        print(f"  {cov:>10.4f}  {kappa:>8.4f}  {f:>9.2f}%{mark}")


# ---------------------------------------------------------------------------
# Check 3 — sawtooth
# ---------------------------------------------------------------------------


def check_sawtooth(
    demand_shape: np.ndarray,
    wind_shape: np.ndarray,
    D_ref: float,
    mu_D: float,
    sigma_D: float,
    rho_D: float,
    P_W_max: float,
    mu_W: float,
    sigma_W: float,
    rho_W: float,
    total_capacity: float,
    T: int,
    chosen_coverage: float,
) -> None:
    kappa = _ar1_kappa(T, chosen_coverage)
    thr_D = kappa * D_ref * sigma_D
    thr_W = kappa * P_W_max * sigma_W

    D_saw = np.where(np.arange(T) % 2 == 0, total_capacity, 0.0)
    xi_D = _demand_innovations(D_saw[np.newaxis, :], demand_shape, mu_D, rho_D, D_ref)[0]
    d_viol = bool(np.any(np.abs(xi_D) > thr_D))

    W_saw = np.where(np.arange(T) % 2 == 0, P_W_max, 0.0)
    xi_W = _wind_innovations(W_saw[np.newaxis, :], wind_shape, mu_W, rho_W, P_W_max)[0]
    w_viol = bool(np.any(np.abs(xi_W) > thr_W))

    print(f"\n  Sawtooth adversarial test (coverage={chosen_coverage}, kappa={kappa:.4f}):")
    print(f"    Demand: max|xi|={np.max(np.abs(xi_D)):.4g}  threshold={thr_D:.4g}  "
          f"REJECTED={d_viol}")
    print(f"    Wind:   max|xi|={np.max(np.abs(xi_W)):.4g}  threshold={thr_W:.4g}  "
          f"REJECTED={w_viol}")
    if not d_viol or not w_viol:
        print("  WARNING: sawtooth NOT fully rejected — coherence should move into the "
              "transport cost.")
    else:
        print("  OK: sawtooth correctly rejected by the AR(1) tube.")


# ---------------------------------------------------------------------------
# Check 4 — innovation-stack and fleet-stack corner tests
# ---------------------------------------------------------------------------


def check_innovation_stack(
    demand_shape: np.ndarray,
    D_ref: float,
    mu_D: float,
    rho_D: float,
    T: int,
    kappa_innov: float,
    kappa_lvl: float,
    sigma_D_innov: float,
    sigma_bar_D: float,
) -> None:
    """Path where every AR(1) innovation equals +kappa_innov*sigma.

    Innovation tube must accept it; level band must reject it.
    """
    # Use (1-1e-9) so the path sits definitively inside the tube despite FP accumulation.
    innov_step = (1.0 - 1e-9) * kappa_innov * sigma_D_innov
    D_stack = np.zeros(T)
    D_stack[0] = D_ref * mu_D * demand_shape[0] + innov_step
    for t in range(1, T):
        ref_inc = D_ref * mu_D * (demand_shape[t] - rho_D * demand_shape[t - 1])
        D_stack[t] = rho_D * D_stack[t - 1] + ref_inc + innov_step

    xi = _demand_innovations(D_stack[np.newaxis, :], demand_shape, mu_D, rho_D, D_ref)[0]
    lvl_dev = _demand_level_dev(D_stack[np.newaxis, :], demand_shape, mu_D, D_ref)[0]

    innov_thr = kappa_innov * sigma_D_innov
    lvl_thr = kappa_lvl * sigma_bar_D

    innov_rejected = bool(np.any(np.abs(xi) > innov_thr))
    lvl_rejected = bool(np.any(np.abs(lvl_dev) > lvl_thr))

    print(f"\n  Innovation-stack test (all innovations at +kappa_innov edge):")
    print(f"    kappa_innov={kappa_innov:.4f}  kappa_lvl={kappa_lvl:.4f}")
    print(f"    Innovation tube: max|xi|={np.max(np.abs(xi)):.4g}  thr={innov_thr:.4g}  "
          f"REJECTED={innov_rejected}  (expected False)")
    print(f"    Level band:      max|dev|={np.max(np.abs(lvl_dev)):.4g}  thr={lvl_thr:.4g}  "
          f"REJECTED={lvl_rejected}  (expected True)")
    if innov_rejected:
        print("  WARNING: stacked path rejected by the innovation tube (unexpected).")
    if not lvl_rejected:
        print("  WARNING: level band failed to reject stacked path — consider raising "
              "CHOSEN_LEVEL_COVERAGE.")
    if not innov_rejected and lvl_rejected:
        print("  OK: level band closes the corner the innovation tube leaves open.")


def check_fleet_stack(
    wind_shape: np.ndarray,
    mu_W: float,
    sigma_W: float,
    rho_W: float,
    wind_gen_data: dict[str, tuple[np.ndarray, float]],
    T: int,
    kappa_innov: float,
    kappa_fleet: float,
    cap_rms_sigma_bar_W: float,
) -> None:
    """Every wind generator simultaneously at its lower innovation edge.

    Per-generator innovation tubes must accept; fleet band must reject.
    """
    fleet_stack = np.zeros(T)
    sum_caps = 0.0
    per_gen_info: list[tuple[str, float, bool]] = []

    for name, (_, cap_i) in wind_gen_data.items():
        innov_step = -(1.0 - 1e-9) * kappa_innov * cap_i * sigma_W  # just inside lower edge
        P_stack = np.zeros(T)
        P_stack[0] = cap_i * mu_W * wind_shape[0] + innov_step
        for t in range(1, T):
            ref_inc = cap_i * mu_W * (wind_shape[t] - rho_W * wind_shape[t - 1])
            P_stack[t] = rho_W * P_stack[t - 1] + ref_inc + innov_step

        xi = _wind_innovations(P_stack[np.newaxis, :], wind_shape, mu_W, rho_W, cap_i)[0]
        innov_thr = kappa_innov * cap_i * sigma_W
        gen_rejected = bool(np.any(np.abs(xi) > innov_thr))
        ratio = float(np.max(np.abs(xi)) / innov_thr) if innov_thr > 0 else float("nan")
        per_gen_info.append((name, ratio, gen_rejected))
        fleet_stack += P_stack
        sum_caps += cap_i

    fleet_dev = fleet_stack - sum_caps * mu_W * wind_shape
    lvl_thr = kappa_fleet * cap_rms_sigma_bar_W
    fleet_rejected = bool(np.any(np.abs(fleet_dev) > lvl_thr))
    per_gen_accepted = not any(rej for _, _, rej in per_gen_info)

    print(f"\n  Fleet-stack test (all generators at lower innovation edge simultaneously):")
    print(f"    kappa_innov={kappa_innov:.4f}  kappa_fleet={kappa_fleet:.4f}")
    for name, ratio, gen_rej in per_gen_info:
        print(f"    {name}: max|xi|/thr={ratio:.4f}  REJECTED={gen_rej}  (expected False)")
    print(f"    Fleet band: max|dev|={np.max(np.abs(fleet_dev)):.4g}  thr={lvl_thr:.4g}  "
          f"REJECTED={fleet_rejected}  (expected True)")
    if not per_gen_accepted:
        print("  WARNING: fleet-stack path rejected by a per-gen innovation tube (unexpected).")
    if not fleet_rejected:
        print("  WARNING: fleet band failed to reject stacked fleet path — consider raising "
              "CHOSEN_FLEET_COVERAGE.")
    if per_gen_accepted and fleet_rejected:
        print("  OK: fleet band closes the corner individual tubes leave open.")


# ---------------------------------------------------------------------------
# Importable calibration function
# ---------------------------------------------------------------------------


def calibrate_support_coverage(
    manager: "ScenarioManager",
    regime_config_path: "str | Path",
    regime_set: str,
    regime_name: str,
    horizon: int,
    n_draws: int,
    seed: int,
    coverage_grid: "list[float]",
) -> dict:
    """Generate n_draws fresh scenarios with `seed`, compute whitened innovations and
    stationary level deviations, sweep coverage_grid,
    and return the smallest single coverage giving 0% rejection across ALL families.

    Returns:
        {
            "regime_name": str,
            "coverage": float | None,   # smallest 0%-rejection coverage; None if none clears
            "kappa": float | None,
            "binding_family": str,      # which family forced the choice
            "per_family_rejection": {family: {coverage: pct}},
            "n_draws": int, "seed": int,
        }
    """
    manager.base_case["time_steps"] = horizon

    calibration_config_path = _single_regime_calibration_config(
        regime_config_path=regime_config_path,
        regime_set=regime_set,
        regime_name=regime_name,
        n_draws=n_draws,
    )
    config_path_for_generation = calibration_config_path or Path(regime_config_path)
    config_set_for_generation = (
        "__support_coverage_calibration__"
        if calibration_config_path is not None
        else regime_set
    )

    try:
        raw = manager.create_scenario_set_from_regimes(
            regime_config_path=str(config_path_for_generation),
            regime_set=config_set_for_generation,
            seed=seed,
        )
    finally:
        if calibration_config_path is not None:
            calibration_config_path.unlink(missing_ok=True)
    df = raw["scenarios_df"]
    if "regime" in df.columns:
        df = df[df["regime"] == regime_name].reset_index(drop=True)
    if len(df) == 0:
        return {
            "regime_name": regime_name, "coverage": None, "kappa": None,
            "binding_family": "no_draws", "per_family_rejection": {}, "n_draws": 0, "seed": seed,
        }
    df = df.iloc[:n_draws].reset_index(drop=True)
    N = len(df)

    if N < n_draws:
        import warnings
        warnings.warn(
            f"calibrate_support_coverage: only {N} draws available for regime '{regime_name}' "
            f"(requested {n_draws}). Calibration may be under-powered.",
            stacklevel=2,
        )

    T = horizon
    mu_D = float(df.at[0, "mu_D"])
    sigma_D = float(df.at[0, "sigma_D"])
    rho_D = float(df.at[0, "rho_D"])
    mu_W = float(df.at[0, "mu_W"])
    sigma_W = float(df.at[0, "sigma_W"])
    rho_W = float(df.at[0, "rho_W"])
    peak_W = float(df.at[0, "peak_W"])
    D_ref = float(manager.base_case["demand"])

    demand_shape = ScenarioManager._build_demand_shape(T)
    wind_shape = ScenarioManager._build_wind_shape(T, peak_W)

    demand_profiles = np.array([_parse_profile(df.at[s, "demand_profile"]) for s in range(N)])
    wind_gen_data = _build_wind_profiles(df, manager, N, T)

    sigma_D_innov = D_ref * sigma_D
    sigma_bar_D = D_ref * sigma_D / np.sqrt(1.0 - rho_D ** 2)

    demand_xi = _demand_innovations(demand_profiles, demand_shape, mu_D, rho_D, D_ref)
    demand_level_dev = _demand_level_dev(demand_profiles, demand_shape, mu_D, D_ref)

    # Build family dict: {name: (deviations (N,T), sigma_scale)}
    families: dict[str, tuple[np.ndarray, float]] = {
        "demand_innov": (demand_xi, sigma_D_innov),
        "demand_level": (demand_level_dev, sigma_bar_D),
    }
    for name, (wp, cap) in wind_gen_data.items():
        xi_w = _wind_innovations(wp, wind_shape, mu_W, rho_W, cap)
        lvl_dev = _wind_level_dev(wp, wind_shape, mu_W, cap)
        families[f"wind_{name}_innov"] = (xi_w, cap * sigma_W)
        families[f"wind_{name}_level"] = (lvl_dev, cap * sigma_W / np.sqrt(1.0 - rho_W ** 2))

    # Sweep: per family, per coverage
    sorted_grid = sorted(coverage_grid)
    per_family_rejection: dict[str, dict[float, float]] = {}
    family_min_coverage: dict[str, float | None] = {}

    for family, (devs, sigma) in families.items():
        per_family_rejection[family] = {}
        first_zero: float | None = None
        for cov in sorted_grid:
            kappa = _ar1_kappa(T, cov)
            pct = _rejection_rate(devs, sigma, kappa) * 100.0
            per_family_rejection[family][cov] = round(pct, 4)
            if pct == 0.0 and first_zero is None:
                first_zero = cov
        family_min_coverage[family] = first_zero

    # Global coverage = max over families (so every family clears at this value).
    clearing = {f: c for f, c in family_min_coverage.items() if c is not None}
    if not clearing:
        return {
            "regime_name": regime_name, "coverage": None, "kappa": None,
            "binding_family": "none_clear",
            "per_family_rejection": per_family_rejection,
            "n_draws": N, "seed": seed,
        }

    global_cov = max(clearing.values())
    # Tie-break: pick the family name alphabetically for determinism.
    binding = min(f for f, c in clearing.items() if c == global_cov)
    global_kappa = _ar1_kappa(T, global_cov)

    return {
        "regime_name": regime_name,
        "coverage": global_cov,
        "kappa": global_kappa,
        "binding_family": binding,
        "per_family_rejection": per_family_rejection,
        "n_draws": N,
        "seed": seed,
    }


def _single_regime_calibration_config(
    regime_config_path: str | Path,
    regime_set: str,
    regime_name: str,
    n_draws: int,
) -> Path | None:
    """Create a temporary one-regime config with n_draws scenarios.

    ScenarioManager takes sample counts from YAML, so calibration needs a
    temporary regime set instead of trusting the possibly tiny DRO runtime set.
    """
    path = Path(regime_config_path)
    with path.open("r", encoding="utf-8") as file_handle:
        raw_config = yaml.safe_load(file_handle) or {}

    regime_sets = raw_config.get("regime_sets")
    if not isinstance(regime_sets, dict) or regime_set not in regime_sets:
        return None

    selected_set = dict(regime_sets[regime_set] or {})
    regimes = selected_set.get("regimes", []) or []
    selected_regime: dict[str, Any] | None = None
    for regime in regimes:
        regime_copy = dict(regime or {})
        if str(regime_copy.get("name")) == str(regime_name):
            regime_copy["n_scenarios"] = int(n_draws)
            selected_regime = regime_copy
            break
    if selected_regime is None:
        return None

    selected_set["regimes"] = [selected_regime]
    calibration_config = {
        key: value
        for key, value in raw_config.items()
        if key not in {"regime_sets", "default_regime_set"}
    }
    calibration_config["default_regime_set"] = "__support_coverage_calibration__"
    calibration_config["regime_sets"] = {
        "__support_coverage_calibration__": selected_set,
    }

    with tempfile.NamedTemporaryFile(
        "w",
        encoding="utf-8",
        suffix=".yaml",
        delete=False,
    ) as temp_file:
        yaml.safe_dump(calibration_config, temp_file, sort_keys=False)
        return Path(temp_file.name)


def print_support_calibration_report(report: dict) -> None:
    print("\n--- Support coverage calibration ---")
    print(
        f"  Regime: {report.get('regime_name')}  "
        f"N={report.get('n_draws')}  seed={report.get('seed')}"
    )
    print(
        f"  Selected coverage={report.get('coverage')}  "
        f"kappa={report.get('kappa')}  binding={report.get('binding_family')}"
    )
    per_family = report.get("per_family_rejection", {}) or {}
    for family in sorted(per_family):
        values = per_family[family]
        row = ", ".join(
            f"{float(cov):.5g}: {float(pct):.4g}%"
            for cov, pct in sorted(values.items(), key=lambda item: float(item[0]))
        )
        print(f"    {family:<22} {row}")


# ---------------------------------------------------------------------------
# Trajectory + bounds plot
# ---------------------------------------------------------------------------


def plot_support_set_bounds(
    demand_profiles: np.ndarray,
    wind_gen_data: dict[str, tuple[np.ndarray, float]],
    demand_shape: np.ndarray,
    wind_shape: np.ndarray,
    D_ref: float,
    mu_D: float,
    sigma_D: float,
    rho_D: float,
    mu_W: float,
    sigma_W: float,
    rho_W: float,
    T: int,
    kappa_ar1: float,
    kappa_lvl: float,
    kappa_fleet: float,
    output_dir: Path,
    source_label: str,
    max_overlay: int = 40,
) -> None:
    """Plot demand and per-generator wind support set bounds.

    Panels show:
      - Sample trajectories (grey, semi-transparent)
      - Innovation-tube reachable envelope: the set of levels reachable if every
        innovation sits at its maximum allowed edge — a growing "trumpet".
      - Stationary level / fleet band: constant-width channel around the reference.
      - Combined support U: intersection of the two (what the MILP actually allows).
      - Deterministic reference trajectory.
      - Worst-case stacked path: innovations always at one edge — inside the tube
        but exits the level/fleet band, illustrating why the new constraints matter.
    """
    t = np.arange(T)
    sigma_D_innov = D_ref * sigma_D
    sigma_bar_D = D_ref * sigma_D / np.sqrt(1.0 - rho_D ** 2)
    sigma_bar_W_scalar = sigma_W / np.sqrt(1.0 - rho_W ** 2)

    caps = [cap for _, (_, cap) in wind_gen_data.items()]
    sum_caps = float(sum(caps))
    cap_rms = float(np.sqrt(sum(c ** 2 for c in caps)))

    # ------------------------------------------------------------------
    # Demand: reference, innovation-tube envelope, level band
    # ------------------------------------------------------------------
    demand_ref = D_ref * mu_D * demand_shape  # (T,)

    # Reachable envelope: recursively propagate ± kappa * sigma at each step.
    # At t=0: cold-start band (same kappa, innovation std).
    # At t≥1: D[t] = rho*D[t-1] + ref_inc + kappa*sigma  (upper),
    #                rho*D[t-1] + ref_inc - kappa*sigma  (lower).
    innov_lo_D = np.zeros(T)
    innov_hi_D = np.zeros(T)
    innov_lo_D[0] = demand_ref[0] - kappa_ar1 * sigma_D_innov
    innov_hi_D[0] = demand_ref[0] + kappa_ar1 * sigma_D_innov
    for s in range(1, T):
        ref_inc = D_ref * mu_D * (demand_shape[s] - rho_D * demand_shape[s - 1])
        innov_lo_D[s] = rho_D * innov_lo_D[s - 1] + ref_inc - kappa_ar1 * sigma_D_innov
        innov_hi_D[s] = rho_D * innov_hi_D[s - 1] + ref_inc + kappa_ar1 * sigma_D_innov

    level_lo_D = demand_ref - kappa_lvl * sigma_bar_D
    level_hi_D = demand_ref + kappa_lvl * sigma_bar_D

    # Combined: intersection + D ≥ 0 physical floor.
    combined_lo_D = np.maximum(np.maximum(innov_lo_D, level_lo_D), 0.0)
    combined_hi_D = np.minimum(innov_hi_D, level_hi_D)

    # Worst-case stacked demand path (innovations at upper edge, just inside tube).
    step_D = (1.0 - 1e-9) * kappa_ar1 * sigma_D_innov
    D_stack = np.empty(T)
    D_stack[0] = demand_ref[0] + step_D
    for s in range(1, T):
        ref_inc = D_ref * mu_D * (demand_shape[s] - rho_D * demand_shape[s - 1])
        D_stack[s] = rho_D * D_stack[s - 1] + ref_inc + step_D

    # ------------------------------------------------------------------
    # Wind fleet: reference, innovation-tube envelope, fleet band
    # ------------------------------------------------------------------
    fleet_ref = sum_caps * mu_W * wind_shape  # (T,)

    # Reachable fleet envelope: all generators simultaneously at ± edge.
    # Per-gen: |xi_i| ≤ kappa * cap_i * sigma_W.  Sum: ≤ kappa * sum_caps * sigma_W.
    fleet_innov_lo = np.zeros(T)
    fleet_innov_hi = np.zeros(T)
    fleet_innov_lo[0] = fleet_ref[0] - kappa_ar1 * sum_caps * sigma_W
    fleet_innov_hi[0] = fleet_ref[0] + kappa_ar1 * sum_caps * sigma_W
    for s in range(1, T):
        ref_inc = sum_caps * mu_W * (wind_shape[s] - rho_W * wind_shape[s - 1])
        fleet_innov_lo[s] = rho_W * fleet_innov_lo[s - 1] + ref_inc - kappa_ar1 * sum_caps * sigma_W
        fleet_innov_hi[s] = rho_W * fleet_innov_hi[s - 1] + ref_inc + kappa_ar1 * sum_caps * sigma_W

    # Fleet level band uses cap_rms (independence-scaled), not sum_caps.
    fleet_level_lo = fleet_ref - kappa_fleet * cap_rms * sigma_bar_W_scalar
    fleet_level_hi = fleet_ref + kappa_fleet * cap_rms * sigma_bar_W_scalar

    # Combined: intersection + fleet ∈ [0, sum_caps].
    combined_fleet_lo = np.maximum(np.maximum(fleet_innov_lo, fleet_level_lo), 0.0)
    combined_fleet_hi = np.minimum(np.minimum(fleet_innov_hi, fleet_level_hi), sum_caps)

    # Worst-case fleet stack: all generators at lower innovation edge simultaneously.
    step_W = (1.0 - 1e-9) * kappa_ar1
    fleet_stack = np.zeros(T)
    for _, (_, cap_i) in wind_gen_data.items():
        P_i = np.empty(T)
        P_i[0] = cap_i * mu_W * wind_shape[0] - step_W * cap_i * sigma_W
        for s in range(1, T):
            ref_inc = cap_i * mu_W * (wind_shape[s] - rho_W * wind_shape[s - 1])
            P_i[s] = rho_W * P_i[s - 1] + ref_inc - step_W * cap_i * sigma_W
        fleet_stack += P_i

    # Sample fleet sums for overlay.
    fleet_profiles_overlay: np.ndarray = sum(  # type: ignore[assignment]
        wp for wp, _ in wind_gen_data.values()
    )

    # ------------------------------------------------------------------
    # Plot
    # ------------------------------------------------------------------
    n_overlay = min(max_overlay, len(demand_profiles))
    n_panels = 1 + len(wind_gen_data)
    fig_height = max(5.0, 4.0 * n_panels)
    fig, axes_raw = plt.subplots(n_panels, 1, figsize=(10, fig_height), sharex=True)
    axes = np.atleast_1d(axes_raw)

    _ORANGE = "#E8820C"
    _GREEN = "#2CA02C"
    _PURPLE = "#7B2D8B"
    _BLUE = "#1F77B4"
    _RED = "#D62728"

    wind_plot_specs = []
    for idx, (gen_name, (wind_profiles, cap_i)) in enumerate(wind_gen_data.items(), start=1):
        wind_ref = cap_i * mu_W * wind_shape
        sigma_W_innov = cap_i * sigma_W
        sigma_bar_W = cap_i * sigma_bar_W_scalar

        innov_lo_W = np.zeros(T)
        innov_hi_W = np.zeros(T)
        innov_lo_W[0] = wind_ref[0] - kappa_ar1 * sigma_W_innov
        innov_hi_W[0] = wind_ref[0] + kappa_ar1 * sigma_W_innov
        for s in range(1, T):
            ref_inc = cap_i * mu_W * (wind_shape[s] - rho_W * wind_shape[s - 1])
            innov_lo_W[s] = rho_W * innov_lo_W[s - 1] + ref_inc - kappa_ar1 * sigma_W_innov
            innov_hi_W[s] = rho_W * innov_hi_W[s - 1] + ref_inc + kappa_ar1 * sigma_W_innov

        level_lo_W = wind_ref - kappa_lvl * sigma_bar_W
        level_hi_W = wind_ref + kappa_lvl * sigma_bar_W
        combined_lo_W = np.maximum(np.maximum(innov_lo_W, level_lo_W), 0.0)
        combined_hi_W = np.minimum(np.minimum(innov_hi_W, level_hi_W), cap_i)

        step_W = (1.0 - 1e-9) * kappa_ar1 * sigma_W_innov
        wind_stack = np.empty(T)
        wind_stack[0] = wind_ref[0] - step_W
        for s in range(1, T):
            ref_inc = cap_i * mu_W * (wind_shape[s] - rho_W * wind_shape[s - 1])
            wind_stack[s] = rho_W * wind_stack[s - 1] + ref_inc - step_W

        wind_plot_specs.append(
            (
                axes[idx], wind_ref,
                innov_lo_W, innov_hi_W,
                level_lo_W, level_hi_W,
                combined_lo_W, combined_hi_W,
                wind_stack,
                wind_profiles[:n_overlay],
                cap_i,
                f"Wind {gen_name}  P[t]  (MW)",
                f"Wind {gen_name} - support set bounds  [{source_label}]",
                f"AR(1) tube envelope  (kappa={kappa_ar1:.2f}, cap*sigma_inn)",
                f"Level band  (kappa={kappa_lvl:.2f}, cap*sigma_bar)",
            )
        )

    for ax, ref, innov_lo, innov_hi, lvl_lo, lvl_hi, comb_lo, comb_hi, stack, overlays, \
            phys_hi, ylabel, title, innov_lbl, lvl_lbl in [
        (
            axes[0], demand_ref,
            innov_lo_D, innov_hi_D,
            level_lo_D, level_hi_D,
            combined_lo_D, combined_hi_D,
            D_stack,
            demand_profiles[:n_overlay],
            None,
            "Demand  D[t]  (MW)",
            f"Demand — support set bounds  [{source_label}]",
            f"AR(1) tube envelope  (κ={kappa_ar1:.2f}, σ_inn)",
            f"Level band  (κ={kappa_lvl:.2f}, σ̄)",
        ),
        (
            axes[1], fleet_ref,
            fleet_innov_lo, fleet_innov_hi,
            fleet_level_lo, fleet_level_hi,
            combined_fleet_lo, combined_fleet_hi,
            fleet_stack,
            fleet_profiles_overlay[:n_overlay],
            sum_caps,
            "Wind fleet  ΣP[t]  (MW)",
            f"Wind fleet — support set bounds  [{source_label}]",
            f"AR(1) tube envelope  (κ={kappa_ar1:.2f}, Σcap·σ_inn)",
            f"Fleet band  (κ={kappa_fleet:.2f}, cap_rms·σ̄)",
        ),
    ][:1] + wind_plot_specs:
        # Sample draws
        for row in overlays:
            ax.plot(t, row, color="silver", lw=0.7, alpha=0.5, zorder=1)

        # Innovation-tube reachable region
        ax.fill_between(t, innov_lo, innov_hi, color=_ORANGE, alpha=0.18,
                        label=innov_lbl, zorder=2)
        ax.plot(t, innov_lo, color=_ORANGE, lw=1.2, ls="--", zorder=3)
        ax.plot(t, innov_hi, color=_ORANGE, lw=1.2, ls="--", zorder=3)

        # Level / fleet band
        ax.fill_between(t, lvl_lo, lvl_hi, color=_GREEN, alpha=0.18,
                        label=lvl_lbl, zorder=2)
        ax.plot(t, lvl_lo, color=_GREEN, lw=1.5, ls="-.", zorder=4)
        ax.plot(t, lvl_hi, color=_GREEN, lw=1.5, ls="-.", zorder=4)

        # Physical limits
        ax.axhline(0.0, color="black", lw=0.9, ls=":", zorder=4)
        if phys_hi is not None:
            ax.axhline(phys_hi, color="black", lw=0.9, ls=":",
                       label=f"Physical cap ({phys_hi:.0f} MW)", zorder=4)

        # Combined support set (intersection)
        ax.plot(t, comb_lo, color=_PURPLE, lw=2.2, label="Combined support U", zorder=5)
        ax.plot(t, comb_hi, color=_PURPLE, lw=2.2, zorder=5)

        # Deterministic reference
        ax.plot(t, ref, color=_BLUE, lw=2.5, label="Reference (det.)", zorder=6)

        # Edge path
        ax.plot(t, stack, color=_RED, lw=2.0, ls="--",
                label="Edge path (inside tube, may exit band)", zorder=6)

        ax.set_ylabel(ylabel)
        ax.set_title(title)
        ax.legend(loc="upper right", fontsize=8.5, framealpha=0.9)
        ax.grid(True, alpha=0.25)
        ax.set_xticks(t)

    axes[-1].set_xlabel("Time step  t")
    fig.tight_layout()
    slug = source_label.lower().replace(" ", "_").replace("(", "").replace(")", "")
    path = output_dir / f"support_set_bounds_by_generator_{slug}.png"
    fig.savefig(path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"  Support set bounds plot saved: {path}")


# ---------------------------------------------------------------------------
# Single-source runner
# ---------------------------------------------------------------------------


def _run_all_checks(
    df: pd.DataFrame,
    manager: ScenarioManager,
    source_label: str,
    output_dir: Path,
) -> None:
    N = len(df)
    T = HORIZON
    mu_D = float(df.at[0, "mu_D"])
    sigma_D = float(df.at[0, "sigma_D"])
    rho_D = float(df.at[0, "rho_D"])
    mu_W = float(df.at[0, "mu_W"])
    sigma_W = float(df.at[0, "sigma_W"])
    rho_W = float(df.at[0, "rho_W"])
    peak_W = float(df.at[0, "peak_W"])
    D_ref = float(manager.base_case["demand"])

    demand_shape = ScenarioManager._build_demand_shape(T)
    wind_shape = ScenarioManager._build_wind_shape(T, peak_W)

    demand_profiles = np.array([_parse_profile(df.at[s, "demand_profile"]) for s in range(N)])
    wind_gen_data = _build_wind_profiles(df, manager, N, T)
    total_capacity = sum(float(g["pmax"]) for g in manager.physical_generators)

    sigma_D_innov = D_ref * sigma_D
    sigma_bar_D = D_ref * sigma_D / np.sqrt(1.0 - rho_D ** 2)  # stationary level std

    demand_xi = _demand_innovations(demand_profiles, demand_shape, mu_D, rho_D, D_ref)
    demand_level_dev = _demand_level_dev(demand_profiles, demand_shape, mu_D, D_ref)

    wind_xi_by_gen: dict[str, np.ndarray] = {}
    sigma_W_by_gen: dict[str, float] = {}
    wind_level_devs_by_gen: dict[str, np.ndarray] = {}
    sigma_bar_W_by_gen: dict[str, float] = {}
    for name, (wp, P_W_max) in wind_gen_data.items():
        wind_xi_by_gen[name] = _wind_innovations(wp, wind_shape, mu_W, rho_W, P_W_max)
        sigma_W_by_gen[name] = P_W_max * sigma_W
        wind_level_devs_by_gen[name] = _wind_level_dev(wp, wind_shape, mu_W, P_W_max)
        sigma_bar_W_by_gen[name] = P_W_max * sigma_W / np.sqrt(1.0 - rho_W ** 2)

    caps = [cap for _, (_, cap) in wind_gen_data.items()]
    sum_caps = float(sum(caps))
    cap_rms = float(np.sqrt(sum(c ** 2 for c in caps)))
    sigma_bar_W_scalar = sigma_W / np.sqrt(1.0 - rho_W ** 2)
    cap_rms_sigma_bar_W = cap_rms * sigma_bar_W_scalar
    sum_caps_sigma_bar_W = sum_caps * sigma_bar_W_scalar

    fleet_profiles: np.ndarray = sum(  # type: ignore[assignment]
        wp for wp, _ in wind_gen_data.values()
    )
    fleet_dev = fleet_profiles - sum_caps * mu_W * wind_shape[np.newaxis, :]

    kappa_chosen = _ar1_kappa(T, CHOSEN_COVERAGE)
    kappa_lvl = _ar1_kappa(T, CHOSEN_LEVEL_COVERAGE)
    kappa_fleet = _ar1_kappa(T, CHOSEN_FLEET_COVERAGE)

    print(f"\n{'=' * 60}")
    print(f"Source: {source_label}  (N={N}, regime='{REGIME_NAME}', T={T})")
    print(f"Regime: mu_D={mu_D}, sigma_D={sigma_D}, rho_D={rho_D}")
    print(f"        mu_W={mu_W}, sigma_W={sigma_W}, rho_W={rho_W}")
    print(f"{'=' * 60}")

    print("\n--- Check 1: Whitened innovations and stationary level deviations ---")
    check_innovations(demand_xi, sigma_D_innov, f"Demand innovations [{source_label}]", output_dir)
    check_innovations(demand_level_dev, sigma_bar_D, f"Demand level [{source_label}]", output_dir)
    for name, xi_w in wind_xi_by_gen.items():
        check_innovations(xi_w, sigma_W_by_gen[name],
                          f"Wind {name} innovations [{source_label}]", output_dir)
    for name, ldev in wind_level_devs_by_gen.items():
        check_innovations(ldev, sigma_bar_W_by_gen[name],
                          f"Wind {name} level [{source_label}]", output_dir)

    print("\n--- Check 2a: AR(1) innovation rejection rate sweep ---")
    check_rejection_rates(demand_xi, wind_xi_by_gen, sigma_D_innov,
                          sigma_W_by_gen, T, CHOSEN_COVERAGE)

    print("\n--- Check 2b: Stationary level band rejection rate sweep ---")
    check_level_rejection_rates(demand_level_dev, wind_level_devs_by_gen, sigma_bar_D,
                                sigma_bar_W_by_gen, T, CHOSEN_LEVEL_COVERAGE)

    print("\n--- Check 2c: Fleet aggregate band ---")
    check_fleet_stats(fleet_dev, cap_rms_sigma_bar_W, sum_caps_sigma_bar_W)
    check_fleet_rejection_rates(fleet_dev, cap_rms_sigma_bar_W, T, CHOSEN_FLEET_COVERAGE)

    print("\n--- Check 3: Sawtooth adversarial test ---")
    first_wind = next(iter(wind_gen_data.values()), None)
    P_W_max_saw = first_wind[1] if first_wind else 0.0
    check_sawtooth(
        demand_shape=demand_shape, wind_shape=wind_shape,
        D_ref=D_ref, mu_D=mu_D, sigma_D=sigma_D, rho_D=rho_D,
        P_W_max=P_W_max_saw, mu_W=mu_W, sigma_W=sigma_W, rho_W=rho_W,
        total_capacity=total_capacity, T=T, chosen_coverage=CHOSEN_COVERAGE,
    )

    print("\n--- Check 4: Innovation-stack and fleet-stack corner tests ---")
    check_innovation_stack(
        demand_shape=demand_shape,
        D_ref=D_ref, mu_D=mu_D, rho_D=rho_D,
        T=T, kappa_innov=kappa_chosen, kappa_lvl=kappa_lvl,
        sigma_D_innov=sigma_D_innov, sigma_bar_D=sigma_bar_D,
    )
    check_fleet_stack(
        wind_shape=wind_shape,
        mu_W=mu_W, sigma_W=sigma_W, rho_W=rho_W,
        wind_gen_data=wind_gen_data,
        T=T, kappa_innov=kappa_chosen, kappa_fleet=kappa_fleet,
        cap_rms_sigma_bar_W=cap_rms_sigma_bar_W,
    )

    print("\n--- Support set bounds plot ---")
    plot_support_set_bounds(
        demand_profiles=demand_profiles,
        wind_gen_data=wind_gen_data,
        demand_shape=demand_shape,
        wind_shape=wind_shape,
        D_ref=D_ref, mu_D=mu_D, sigma_D=sigma_D, rho_D=rho_D,
        mu_W=mu_W, sigma_W=sigma_W, rho_W=rho_W,
        T=T, kappa_ar1=kappa_chosen, kappa_lvl=kappa_lvl, kappa_fleet=kappa_fleet,
        output_dir=output_dir, source_label=source_label,
    )

    d_rej = _rejection_rate(demand_xi, sigma_D_innov, kappa_chosen) * 100
    w_rej = max(
        (_rejection_rate(xi, sigma_W_by_gen[g], kappa_chosen) * 100
         for g, xi in wind_xi_by_gen.items()),
        default=float("nan"),
    )
    d_lvl_rej = _rejection_rate(demand_level_dev, sigma_bar_D, kappa_lvl) * 100
    w_lvl_rej = max(
        (_rejection_rate(dev, sigma_bar_W_by_gen[g], kappa_lvl) * 100
         for g, dev in wind_level_devs_by_gen.items()),
        default=float("nan"),
    )
    f_rej = _rejection_rate(fleet_dev, cap_rms_sigma_bar_W, kappa_fleet) * 100
    print(f"\n--- Summary [{source_label}] ---")
    print(f"  AR(1) innovations:   coverage={CHOSEN_COVERAGE}  kappa={kappa_chosen:.4f}")
    print(f"    Demand: {d_rej:.2f}%  Wind (max): {w_rej:.2f}%  (target 0%)")
    print(f"  Level band:          coverage={CHOSEN_LEVEL_COVERAGE}  kappa={kappa_lvl:.4f}")
    print(f"    Demand: {d_lvl_rej:.2f}%  Wind (max): {w_lvl_rej:.2f}%  (target 0%)")
    print(f"  Fleet band:          coverage={CHOSEN_FLEET_COVERAGE}  kappa={kappa_fleet:.4f}")
    print(f"    Fleet: {f_rej:.2f}%  (target 0%)")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    manager = ScenarioManager(CASE)
    manager.base_case["time_steps"] = HORIZON

    if RUN_SUPPORT_COVERAGE_CALIBRATION:
        calibration_report = calibrate_support_coverage(
            manager=manager,
            regime_config_path=REGIME_CONFIG,
            regime_set=REGIME_SET,
            regime_name=REGIME_NAME,
            horizon=HORIZON,
            n_draws=CALIBRATION_N_DRAWS,
            seed=CALIBRATION_SEED,
            coverage_grid=COVERAGE_GRID,
        )
        print_support_calibration_report(calibration_report)
        SUPPORT_CALIBRATION_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with SUPPORT_CALIBRATION_REPORT_PATH.open("w", encoding="utf-8") as file_handle:
            json.dump(calibration_report, file_handle, indent=2)
        print(f"  Calibration report saved: {SUPPORT_CALIBRATION_REPORT_PATH}")

    if EXISTING_SCENARIOS_CSV is not None and EXISTING_SCENARIOS_CSV.exists():
        print(f"\nLoading existing DRO scenarios from {EXISTING_SCENARIOS_CSV}")
        existing_df = pd.read_csv(EXISTING_SCENARIOS_CSV)
        if "regime" in existing_df.columns:
            existing_df = existing_df[existing_df["regime"] == REGIME_NAME].reset_index(drop=True)
        if len(existing_df) == 0:
            print(f"  No rows for regime '{REGIME_NAME}' — skipping existing-scenario check.")
        else:
            _run_all_checks(existing_df, manager, "existing DRO scenarios", OUTPUT_DIR)
    else:
        if EXISTING_SCENARIOS_CSV is not None:
            print(f"\nExisting-scenarios CSV not found: {EXISTING_SCENARIOS_CSV}")
        print("Skipping existing-scenario check.")

    print(f"\nGenerating {N_DRAWS} fresh draws (seed={VERIFY_SEED}) ...")
    raw = manager.create_scenario_set_from_regimes(
        regime_config_path=str(REGIME_CONFIG),
        regime_set=REGIME_SET,
        seed=VERIFY_SEED,
    )
    fresh_df = raw["scenarios_df"]
    if "regime" in fresh_df.columns:
        fresh_df = fresh_df[fresh_df["regime"] == REGIME_NAME].reset_index(drop=True)
    if len(fresh_df) == 0:
        print(f"No scenarios generated for regime '{REGIME_NAME}'. "
              f"Available: {raw['scenarios_df']['regime'].unique().tolist()}")
        return
    fresh_df = fresh_df.iloc[:N_DRAWS].reset_index(drop=True)
    _run_all_checks(fresh_df, manager, "fresh draws (unconstrained)", OUTPUT_DIR)


if __name__ == "__main__":
    main()
